### ISSUE TITLE
WRONGTPE error on Upstash

### ISSUE THREAD

**Issue by mountainash** [ginetta/go#1]
```
UpstashError: WRONGTYPE Operation against a key holding the wrong kind of value
    at node_modules/@upstash/redis/esm/pkg/http.js:73:0
    at node_modules/@upstash/redis/esm/pkg/commands/command.js:46:32 {
  name: 'UpstashError'
}
```
From: https://vercel.com/ginetta/go/DaajKkFwe3a4PEd9PN2D88uoum9M/logs?page=1&timeline=past30Minutes&startDate=1681911359730&endDate=1681913159730&selectedLogId=1681913153104996564641700000&selectedLogTimestamp=1681913153104&forceEndDate=1681913153104

**Comment by mountainash** [comment]
Logged into the Upstash account but can't see any services setup.

Email to @samspycher:

> Hello Sam... could you please check that the Ginetta Upstash account can access the Redis DB? I can't see any DB's in the account and think that it might be created in your personal account

**Comment by mountainash** [comment]
@samspycher "I have also made [infra@ginetta.net](mailto:infra@ginetta.net) owner of the Ginetta team, so you should be able to add/remove members as you see fit"

Closing - DB was sleeping. Added as known issue on wiki.
